### ISSUE TITLE
Unspecified

### ISSUE THREAD

**Issue by ucmafialtd** [instamobile/react-native-starter-kit#19]
![69623333-50C7-4789-90D8-A2BF4004BC83](https://user-images.githubusercontent.com/53587701/105571769-8e63ee00-5d07-11eb-80a4-582c15556ac3.png)
![2049DDB9-ABA0-4908-88E1-34076925DAC9](https://user-images.githubusercontent.com/53587701/105571771-90c64800-5d07-11eb-87a8-ab920c0974d1.png)

**Comment by mrcflorian** [comment]
Please contact customer support and simply ask for a refund. Thanks!
